### ISSUE TITLE
Incorrect cron calculation in croniter when DST changed

### ISSUE THREAD

**Issue by kkujawinski** [gawel/aiocron#7]
`Croniter` incorrectly calculate next cron hit if DST change occurs.

The reason is giving `dateutil.tz.tzlocal` object in initial datetime. You can read criticsm about here http://www.assert.cc/2014/05/25/which-python-time-zone-library.html.

I have already fixed this issue and I added proper test case.

Env: Ubuntu 14.04

**Comment by gawel** [comment]
Isn't that more related to https://github.com/kiorky/croniter ?

**Comment by gawel** [comment]
Oh no, didn't look at your patch. Nice one.

**Comment by kkujawinski** [comment]
IMO it is more related to `dateutil.tz.tzlocal`. Check the article I've pasted.

**Comment by st31ny** [comment]
I noticed today in the morning that after the DST change tonight aiocron fired at the wrong times, and continued to do so. This issue is still open, although #8 has been merged, so I wonder if the behaviour I observed is a new issue, or if this one has not been fully fixed yet.

I am using aiocron version 1.3 on python 3.5 with dateutil version 2.5.3.

**Comment by st31ny** [comment]
I did some tests with a [small test script](https://gist.github.com/st31ny/a067db8896340c2df4b40a3e0adea2e9) and noticed a very interesting behaviour:
```
$ faketime '2020-03-29 1:58:55' ./aiocron-test.py                                                                                                                    
start running at: 2020-03-29T01:58:55.439818+01:00
fired 59 1 * * * 59 at 2020-03-29T01:59:59.024419+01:00
fired 0 2 * * * at 2020-03-29T03:00:00.002449+02:00
```
```
$ faketime '2020-03-29 1:59:55' ./aiocron-test.py                                                                                                                    
start running at: 2020-03-29T01:59:55.687915+01:00
fired 59 1 * * * 59 at 2020-03-29T01:59:59.003210+01:00
fired 0 3 * * * at 2020-03-29T03:00:00.002315+02:00
```
Notice how a different job fires whether I start at 1:59:55 or 1:58:55.
I could reproduce that on two machines with different versions:
* Python 3.5.3, dateutil 2.5.3, tzlocal 1.3, aiocron 1.3, croniter 0.3.12
* Python 3.7.5, dateutil 2.7.3, tzlocal 2.1, aiocron 1.3, croniter 0.3.30

Both machines are set to CEST.

**Comment by gawel** [comment]
It the last time that this may occurs AFAIK. We'll never change again (at least in UE)

**Comment by Pigueiras** [comment]
We've just hit this today 😭 . Wasn't this fixed by: https://github.com/taichino/croniter/pull/135? With  `croniter==1.0.15` also happens.

**Comment by gawel** [comment]
Looks like it was'nt. Just like UE laws :D

I really don't want to dig into this since those hour changes should disappear at some point... Next year?

Of course I'll be happy if someone provide a PR if the problem come from aiocron

**Comment by st31ny** [comment]
> I really don't want to dig into this since those hour changes should disappear at some point... Next year?
That's what I'm looking for, too. Until then, I just have a reminder in my calendar to restart things after the DST change…

**Comment by st31ny** [comment]
The bug still exists in version 1.8 is persistent even after multiple runs. So, my cron job is scheduled at 7:15 but since the DST change it was executed twice at 8:15… Probably, I'll have to restart the service.

**Comment by st31ny** [comment]
Apparently, it's still a bug in croniter: https://github.com/kiorky/croniter/issues/91

**Comment by st31ny** [comment]
As a workaround, set the timezone explicitly using pytz.
